# Generated by Django 4.1.3 on 2022-11-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('shorturl', models.CharField(max_length=10)),
                ('creator', models.IntegerField()),
                ('token', models.CharField(max_length=20)),
            ],
        ),
    ]
