# Generated by Django 4.1.3 on 2022-11-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='shorturl',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
