# Generated by Django 4.1.3 on 2022-11-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_urlmodel_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
