# Generated by Django 4.1.3 on 2022-11-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_urlmodel_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='creator',
            field=models.IntegerField(null=True),
        ),
    ]
