# Generated by Django 4.1.3 on 2022-11-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_urlmodel_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='token',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
