# Generated by Django 4.1.3 on 2022-11-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_urlmodel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='creator',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='token',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
