# Generated by Django 4.1.3 on 2022-11-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_urlmodel_creator_alter_urlmodel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='creator',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='token',
            field=models.CharField(max_length=20),
        ),
    ]
