# Generated by Django 4.1.3 on 2022-11-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_urlmodel_urlmodels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLModels',
            new_name='URLModel',
        ),
    ]
