# Generated by Django 4.1.3 on 2022-11-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_urlmodels_urlmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLModel',
        ),
    ]
