# Generated by Django 4.1.3 on 2022-11-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
