# Generated by Django 4.1.3 on 2022-11-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_urlmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmodel',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='urlmodel',
            name='token',
        ),
    ]
