# Generated by Django 4.1.3 on 2022-11-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_urlmodel_creator_remove_urlmodel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='creator',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='token',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
