# Generated by Django 4.1.3 on 2022-11-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_urlmodel_creator_urlmodel_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURLs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('shorturl', models.CharField(max_length=10, unique=True)),
                ('creator', models.IntegerField(default=None)),
                ('token', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='URLModel',
        ),
    ]
