# Generated by Django 4.1.3 on 2022-11-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_shorturls_delete_urlmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturls',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
